import type { Metadata } from "next";
import "../globals.css";
import Notif from "./notif";

export const metadata: Metadata = {
  title: "Test project",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='font-main bg-slate-100 text-slate-950 tabular-nums min-h-dvh'>
        {children}
        <Notif />  
      </body>
    </html>
  );
}
